source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.3'

pod 'AWSCore', '2.3.5'
pod 'AWSAutoScaling', '2.3.5'
pod 'AWSCloudWatch', '2.3.5'
pod 'AWSDynamoDB', '2.3.5'
pod 'AWSEC2', '2.3.5'
pod 'AWSElasticLoadBalancing', '2.3.5'
pod 'AWSKinesis', '2.3.5'
pod 'AWSLambda', '2.3.5'
pod 'AWSMachineLearning', '2.3.5'
pod 'AWSMobileAnalytics', '2.3.5'
pod 'AWSS3', '2.3.5'
pod 'AWSSES', '2.3.5'
pod 'AWSSimpleDB', '2.3.5'
pod 'AWSSNS', '2.3.5'
pod 'AWSSQS', '2.3.5'
pod 'AWSCognito', '2.3.5'

pod 'Buglife'
pod 'AFNetworking'
